#!/bin/bash
apt-get update -y
bash <(curl -Ls https://raw.githubusercontent.com/TranCuongQ4/X-UI/master/install.sh)
ufw allow 54321
ufw allow 443
ufw allow 80
ufw allow 80/tcp
curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
sudo apt-get install speedtest
clear
speedtest
echo ""
echo ""
echo " -----------------Đã Cài Đặt Thành Công X-UI----------------- "  
echo " Vui Lòng Vào Trình Duyệt Nhập IP VPS Và Thêm Vào Đuôi IP Là :54321 "
echo " Bây Giờ Bạn Vào X-UI Sửa Thông Tin Và Tạo Vmess Trojan Vless Đợi Gì Nữa Nào "
echo " User admin & Pass admin. Nhớ Đổi Hết Thông Tin Tránh Bị Mất "
echo ""
echo " Cách Tạo File "
echo " Chọn Dòng Thứ 2 (Danh Sách Đến) "
echo " Bấm Dấu + "
echo " Dòng 1 Nhận Xét Là Tên File "
echo " Hải Cảng Bạn Sửa Thành Port Mà Bạn Muốn File Chạy (sử dụng 1 trong 2 port đã mở là 443 hoặc 80) "
echo " Bật http giả mạo "
echo " Bấm Dấu + Cạnh Tiêu Đề Yêu Cầu "
echo " Nhập Payload Viettell Vào Ô Giá Trị "
echo ""
echo " Các Bạn Có Thể Chọn 1 Payload Mình Để Bên Dưới "
echo " videoakm1.tv360.vn "
echo " videoakm2.tv360.vn "
echo " imageakm1.tv360.vn "
echo " imageakm2.tv360.vn "
echo ""
echo " Các Bạn Tắt Nút Đánh Hơi Để Fix Zalo Sau Đó Ấn Vào Ô Thêm Vào Để Hoàn Thành Tạo File "
echo " Sau Khi Hoàn Thành File Sẽ Được Tạo Trong Danh Sách "
echo ""
echo " Bấm Chữ Chạy Ở Đầu File Chọn Dòng Đầu Tiên Để Xem mã QR và Lấy Code "
echo " Cuối Cùng Các Bạn Vào App Napsternetv Và Quét Mã QR Hoặc Dán Code "
echo " Bấm Vào File Và Chạy Thui ^^ "
echo ""
echo " Liên Hệ Với Đậu Đậu Qua Zalo Để Được Hỗ Trợ Nhé: 0983538806 "
echo " Vào Nhóm Zalo Chúng Tôi Cùng Giao Lưu Nhé : https://zalo.me/g/nlsmbo197 "
echo " ============ CHÚC CÁC BẠN THÀNH CÔNG ============ "
echo ""
