#!/bin/bash
apt-get update -y
bash <(curl -Ls https://raw.githubusercontent.com/TranCuongQ4/X-UI/master/install.sh)
ufw allow 54321
ufw allow 443
ufw allow 80
ufw allow 80/tcp
clear
echo ""
echo ""
echo " ----------------- ĐÃ CÀI ĐẶT THÀNH CÔNG X-UI ----------------- "  
echo ""
echo " Vui Lòng Vào Trình Duyệt Nhập IP VPS Và Thêm Vào Đuôi IP Là :54321 "
echo " Bây Giờ Bạn Vào X-UI Sửa Thông Tin Và Tạo Vmess Trojan Vless Đợi Gì Nữa Nào "
echo " User admin & Pass admin. Nhớ Đổi Hết Thông Tin Tránh Bị Mất "
echo " ------------------------------------------------------- "
echo " Các Bạn Tắt Nút Đánh Hơi Để Fix Zalo Nhé! "
echo " ------------------------------------------------------- "
echo " Liên Hệ Với Đậu Đậu Qua Zalo Để Được Hỗ Trợ Nhé: 0983538806 "
echo " =============== CHÚC CÁC BẠN THÀNH CÔNG =============== "
echo ""
