#!/bin/bash
apt-get update -y
bash <(curl -Ls https://raw.githubusercontent.com/TranCuongQ4/X-UI/master/install.sh)
ufw allow 54321
ufw allow 443
ufw allow 80
ufw allow 80/tcp
clear
echo ""
echo " ---------------- ĐÃ CÀI ĐẶT THÀNH CÔNG X-UI ---------------- "  
echo ""
echo "  Vui lòng vào trình duyệt nhập IP VPS và thêm vào đuôi IP là :54321 "
echo "  Bây giờ bạn vào X-UI sửa thông tin và tạo vmess trojan vless "
echo "  User: admin & Pass: admin. nhớ đổi hết thông tin tránh bị mất "
echo " ------------------------------------------------------------ "
echo "  Các bạn tắt nút đánh hơi để fix zalo nhé! "
echo " ------------------------------------------------------------ "
echo "  Liên hệ với Đậu Đậu qua zalo để được hỗ trợ nhé: 0983538806  "
echo " ================= CHÚC CÁC BẠN THÀNH CÔNG ================== "
