#!/bin/bash

set -u

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m'

SQUID_CONF="/etc/squid/squid.conf"
PASSWD_FILE="/etc/squid/passwd"
USERS_FILE="/etc/squid/users.txt"

pause() {
    read -r -p "Nhấn Enter để tiếp tục..."
}

msg() {
    local color="$1"
    shift
    echo -e "${color}$*${NC}"
}

center_text() {
    local text="$1"
    local width=55
    local text_len=${#text}
    local padding=$(( (width - text_len) / 2 ))
    (( padding < 0 )) && padding=0
    printf "%${padding}s%s\n" "" "$text"
}

require_root() {
    if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
        msg "$RED" "[!] Vui lòng chạy script bằng quyền root."
        exit 1
    fi
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

ensure_packages() {
    local missing=()
    for cmd in squid htpasswd iptables ip awk sed grep systemctl; do
        command_exists "$cmd" || missing+=("$cmd")
    done

    if [[ ${#missing[@]} -eq 0 && -d /etc/squid ]]; then
        return 0
    fi

    msg "$WHITE" "[-] Đang cài đặt Squid và gói cần thiết..."
    apt update >/dev/null 2>&1 || true
    apt install -y squid apache2-utils iproute2 iptables >/dev/null 2>&1

    if [[ ! -d /etc/squid ]]; then
        msg "$RED" "[!] Không cài được Squid."
        exit 1
    fi
}

ensure_files() {
    mkdir -p /etc/squid
    touch "$PASSWD_FILE"
    chmod 640 "$PASSWD_FILE"
    chown proxy:proxy "$PASSWD_FILE" 2>/dev/null || true

    touch "$USERS_FILE"
    chmod 600 "$USERS_FILE"
}

list_ipv4s() {
    {
        ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1
        ip -4 -o addr show 2>/dev/null | awk '{print $4}' | cut -d/ -f1
        ip a 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1
        hostname -I 2>/dev/null | tr ' ' '\n'
    } | awk 'NF && $1 != "127.0.0.1" && $1 !~ /^169\.254\./' | sort -u
}

list_proxies() {
    [[ -f "$SQUID_CONF" ]] || return 0
    awk '/^http_port[[:space:]]+[0-9.]+:[0-9]+$/ {print $2}' "$SQUID_CONF"
}

list_users() {
    [[ -s "$PASSWD_FILE" ]] || return 0
    awk -F: 'NF {print $1}' "$PASSWD_FILE"
}

proxy_count() {
    list_proxies | wc -l
}

user_count() {
    list_users | wc -l
}

port_exists() {
    local port="$1"
    list_proxies | awk -F: -v p="$port" '$2==p {found=1} END{exit !found}'
}

ip_exists_in_proxies() {
    local ip="$1"
    list_proxies | awk -F: -v v="$ip" '$1==v {found=1} END{exit !found}'
}

get_unadded_ips() {
    local ip
    for ip in $(list_ipv4s); do
        if ! ip_exists_in_proxies "$ip"; then
            echo "$ip"
        fi
    done
}

render_config() {
    local proxies="$1"
    cat > "$SQUID_CONF" <<EOF
# Generated by Proxy-Manager
# All authenticated users can use all configured proxies below.

auth_param basic program /usr/lib/squid/basic_ncsa_auth $PASSWD_FILE
auth_param basic realm Proxy Authentication
acl authenticated proxy_auth REQUIRED

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow authenticated
http_access deny all

EOF

    if [[ -n "$proxies" ]]; then
        while IFS= read -r proxy; do
            [[ -n "$proxy" ]] && echo "http_port $proxy" >> "$SQUID_CONF"
        done <<< "$proxies"
    fi
}

iptables_allow_port() {
    local port="$1"
    iptables -C INPUT -p tcp --dport "$port" -j ACCEPT >/dev/null 2>&1 || \
        iptables -I INPUT -p tcp --dport "$port" -j ACCEPT >/dev/null 2>&1
}

iptables_remove_port() {
    local port="$1"
    while iptables -C INPUT -p tcp --dport "$port" -j ACCEPT >/dev/null 2>&1; do
        iptables -D INPUT -p tcp --dport "$port" -j ACCEPT >/dev/null 2>&1 || break
    done
}

restart_squid() {
    systemctl restart squid >/dev/null 2>&1
}

validate_port() {
    local port="$1"
    [[ "$port" =~ ^[0-9]+$ ]] || return 1
    (( port >= 1 && port <= 65535 ))
}

random_port() {
    local p tries=0
    while (( tries < 100 )); do
        p=$((RANDOM % 40000 + 20000))
        if ! port_exists "$p"; then
            echo "$p"
            return 0
        fi
        tries=$((tries + 1))
    done
    echo "3128"
}

select_from_list() {
    local prompt="$1"
    shift
    local items=("$@")
    local i choice

    if [[ ${#items[@]} -eq 0 ]]; then
        return 1
    fi

    for i in "${!items[@]}"; do
        echo " [$((i+1))] ${items[$i]}" >&2
    done

    read -r -p "$prompt" choice </dev/tty >&2
    if [[ ! "$choice" =~ ^[0-9]+$ ]] || (( choice < 1 || choice > ${#items[@]} )); then
        return 1
    fi

    printf '%s\n' "${items[$((choice-1))]}"
}

sync_users_file() {
    : > "$USERS_FILE"
    while IFS= read -r user; do
        [[ -n "$user" ]] && echo "$user" >> "$USERS_FILE"
    done < <(list_users)
    chmod 600 "$USERS_FILE"
}

create_first_user_if_needed() {
    if [[ -s "$PASSWD_FILE" ]]; then
        return 0
    fi

    msg "$WHITE" "[-] Tạo user auth đầu tiên (user này dùng chung cho tất cả proxy)."
    local username password
    while true; do
        read -r -p "-> Nhập username đầu tiên: " username
        [[ -n "$username" ]] && break
        msg "$RED" "[!] Username không được để trống."
    done
    while true; do
        read -r -p "-> Nhập password đầu tiên: " password
        [[ -n "$password" ]] && break
        msg "$RED" "[!] Password không được để trống."
    done

    htpasswd -b -c "$PASSWD_FILE" "$username" "$password" >/dev/null 2>&1 || {
        msg "$RED" "[!] Không tạo được user đầu tiên."
        exit 1
    }
    chown proxy:proxy "$PASSWD_FILE" 2>/dev/null || true
    chmod 640 "$PASSWD_FILE"
    sync_users_file
}

display_header() {
    local status="Không chạy"
    if systemctl is-active --quiet squid; then
        status="Đang chạy"
    fi

    echo -e "[Trạng thái Proxy: $status | Proxy: $(proxy_count) | User chung: $(user_count)]"
}

initial_setup() {
    local proxies existing
    existing="$(list_proxies)"
    if [[ -n "$existing" ]]; then
        return 0
    fi

    msg "$WHITE" "[-] Chưa có proxy nào. Tiến hành cấu hình proxy đầu tiên..."
    local ips=()
    mapfile -t ips < <(list_ipv4s)
    if [[ ${#ips[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không tìm thấy IP IPv4 nào trên máy."
        exit 1
    fi

    echo "Danh sách IP có thể bind proxy:"
    local ip
    ip=$(select_from_list "-> Chọn số thứ tự IP để tạo proxy đầu tiên: " "${ips[@]}") || {
        msg "$RED" "[!] Lựa chọn không hợp lệ."
        exit 1
    }

    local port default_port
    default_port="$(random_port)"
    read -r -p "-> Nhập port cho proxy đầu tiên [${default_port}]: " port
    port="${port:-$default_port}"
    if ! validate_port "$port" || port_exists "$port"; then
        msg "$RED" "[!] Port không hợp lệ hoặc đã tồn tại."
        exit 1
    fi

    render_config "${ip}:${port}"
    iptables_allow_port "$port"
    create_first_user_if_needed
    restart_squid

    if systemctl is-active --quiet squid; then
        msg "$GREEN" "[+] Tạo proxy đầu tiên thành công: ${ip}:${port}"
    else
        msg "$RED" "[!] Squid chưa khởi động thành công."
    fi
    pause
}

add_proxy() {
    local ips=()
    mapfile -t ips < <(get_unadded_ips)
    if [[ ${#ips[@]} -eq 0 ]]; then
        msg "$RED" "[!] Tất cả IP đã được add proxy."
        pause
        return
    fi

    echo "Danh sách IP chưa có proxy:"
    local ip
    ip=$(select_from_list "-> Chọn số thứ tự IP để add proxy: " "${ips[@]}") || {
        msg "$RED" "[!] Lựa chọn không hợp lệ."
        pause
        return
    }

    local default_port port proxies
    default_port="$(random_port)"
    read -r -p "-> Nhập port [${default_port}]: " port
    port="${port:-$default_port}"

    if ! validate_port "$port"; then
        msg "$RED" "[!] Port không hợp lệ."
        pause
        return
    fi
    if port_exists "$port"; then
        msg "$RED" "[!] Port đã tồn tại trong danh sách proxy."
        pause
        return
    fi

    proxies="$(list_proxies)"
    proxies+=$'\n'"${ip}:${port}"
    proxies="$(printf '%s\n' "$proxies" | awk 'NF' | sort -u)"
    render_config "$proxies"
    iptables_allow_port "$port"
    restart_squid

    if systemctl is-active --quiet squid; then
        msg "$GREEN" "[+] Thêm proxy thành công: ${ip}:${port}"
    else
        msg "$RED" "[!] Squid restart lỗi sau khi thêm proxy."
    fi
    pause
}

edit_proxy() {
    local proxies=()
    mapfile -t proxies < <(list_proxies)
    if [[ ${#proxies[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không có proxy nào để chỉnh sửa."
        pause
        return
    fi

    echo "Danh sách proxy hiện có:"
    local selected old_ip old_port new_ip new_port available_ips=()
    selected=$(select_from_list "-> Chọn số thứ tự proxy để chỉnh sửa: " "${proxies[@]}") || {
        msg "$RED" "[!] Lựa chọn không hợp lệ."
        pause
        return
    }

    old_ip="${selected%%:*}"
    old_port="${selected##*:}"

    mapfile -t available_ips < <(printf '%s\n' "$old_ip" && get_unadded_ips | awk 'NF')
    mapfile -t available_ips < <(printf '%s\n' "${available_ips[@]}" | awk 'NF' | sort -u)

    echo "Danh sách IP có thể dùng (IP hiện tại luôn được phép giữ nguyên):"
    new_ip=$(select_from_list "-> Chọn IP mới: " "${available_ips[@]}") || {
        msg "$RED" "[!] Lựa chọn không hợp lệ."
        pause
        return
    }

    read -r -p "-> Nhập cổng mới [${old_port}]: " new_port
    new_port="${new_port:-$old_port}"

    if ! validate_port "$new_port"; then
        msg "$RED" "[!] Port không hợp lệ."
        pause
        return
    fi
    if [[ "$new_port" != "$old_port" ]] && port_exists "$new_port"; then
        msg "$RED" "[!] Port mới đã tồn tại."
        pause
        return
    fi

    local updated=() proxy
    for proxy in "${proxies[@]}"; do
        if [[ "$proxy" == "$selected" ]]; then
            updated+=("${new_ip}:${new_port}")
        else
            updated+=("$proxy")
        fi
    done

    render_config "$(printf '%s\n' "${updated[@]}" | awk 'NF' | sort -u)"
    if [[ "$new_port" != "$old_port" ]]; then
        iptables_remove_port "$old_port"
        iptables_allow_port "$new_port"
    fi
    restart_squid

    if systemctl is-active --quiet squid; then
        msg "$GREEN" "[+] Cập nhật proxy thành công: ${new_ip}:${new_port}"
    else
        msg "$RED" "[!] Squid restart lỗi sau khi sửa proxy."
    fi
    pause
}

delete_proxy() {
    local proxies=()
    mapfile -t proxies < <(list_proxies)
    if [[ ${#proxies[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không có proxy nào để xóa."
        pause
        return
    fi

    echo "Danh sách proxy hiện có:"
    local selected updated=() proxy port
    selected=$(select_from_list "-> Chọn số thứ tự proxy để xóa: " "${proxies[@]}") || {
        msg "$RED" "[!] Lựa chọn không hợp lệ."
        pause
        return
    }

    for proxy in "${proxies[@]}"; do
        [[ "$proxy" != "$selected" ]] && updated+=("$proxy")
    done

    port="${selected##*:}"
    render_config "$(printf '%s\n' "${updated[@]}" | awk 'NF' | sort -u)"
    iptables_remove_port "$port"
    restart_squid

    if systemctl is-active --quiet squid || [[ ${#updated[@]} -eq 0 ]]; then
        msg "$GREEN" "[+] Xóa proxy ${selected} thành công."
    else
        msg "$RED" "[!] Squid restart lỗi sau khi xóa proxy."
    fi
    pause
}

add_user() {
    msg "$WHITE" "[-] User mới sẽ dùng chung cho tất cả proxy hiện có."
    local username password
    read -r -p "-> Nhập username mới: " username
    if [[ -z "$username" ]]; then
        msg "$RED" "[!] Username không được để trống."
        pause
        return
    fi
    if list_users | grep -Fxq "$username"; then
        msg "$RED" "[!] Username '$username' đã tồn tại."
        pause
        return
    fi

    read -r -p "-> Nhập password mới: " password
    if [[ -z "$password" ]]; then
        msg "$RED" "[!] Password không được để trống."
        pause
        return
    fi

    htpasswd -b "$PASSWD_FILE" "$username" "$password" >/dev/null 2>&1 || {
        msg "$RED" "[!] Không thêm được user."
        pause
        return
    }
    chown proxy:proxy "$PASSWD_FILE" 2>/dev/null || true
    chmod 640 "$PASSWD_FILE"
    sync_users_file
    restart_squid
    msg "$GREEN" "[+] Thêm user $username thành công."
    pause
}

edit_user() {
    local users=()
    mapfile -t users < <(list_users)
    if [[ ${#users[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không có user nào để chỉnh sửa."
        pause
        return
    fi

    echo "Danh sách user hiện có:"
    local selected new_username new_password
    selected=$(select_from_list "-> Chọn số thứ tự user để chỉnh sửa: " "${users[@]}") || {
        msg "$RED" "[!] Lựa chọn không hợp lệ."
        pause
        return
    }

    read -r -p "-> Nhập username mới (Enter để giữ nguyên): " new_username
    new_username="${new_username:-$selected}"

    if [[ "$new_username" != "$selected" ]] && list_users | grep -Fxq "$new_username"; then
        msg "$RED" "[!] Username mới đã tồn tại."
        pause
        return
    fi

    read -r -p "-> Nhập password mới (bắt buộc nếu đổi username, Enter để bỏ qua): " new_password

    if [[ "$new_username" != "$selected" && -z "$new_password" ]]; then
        msg "$RED" "[!] Đổi username thì bắt buộc phải nhập password mới."
        pause
        return
    fi

    if [[ "$new_username" == "$selected" && -z "$new_password" ]]; then
        msg "$YELLOW" "[!] Không có thay đổi nào."
        pause
        return
    fi

    if [[ "$new_username" != "$selected" ]]; then
        htpasswd -D "$PASSWD_FILE" "$selected" >/dev/null 2>&1 || true
        htpasswd -b "$PASSWD_FILE" "$new_username" "$new_password" >/dev/null 2>&1 || {
            msg "$RED" "[!] Không cập nhật được user."
            pause
            return
        }
    else
        htpasswd -b "$PASSWD_FILE" "$selected" "$new_password" >/dev/null 2>&1 || {
            msg "$RED" "[!] Không cập nhật được password user."
            pause
            return
        }
    fi

    chown proxy:proxy "$PASSWD_FILE" 2>/dev/null || true
    chmod 640 "$PASSWD_FILE"
    sync_users_file
    restart_squid
    msg "$GREEN" "[+] Cập nhật user thành công: $selected -> $new_username"
    pause
}

delete_user() {
    local users=()
    mapfile -t users < <(list_users)
    if [[ ${#users[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không có user nào để xóa."
        pause
        return
    fi

    echo "Danh sách user hiện có:"
    local selected
    selected=$(select_from_list "-> Chọn số thứ tự user để xóa: " "${users[@]}") || {
        msg "$RED" "[!] Lựa chọn không hợp lệ."
        pause
        return
    }

    htpasswd -D "$PASSWD_FILE" "$selected" >/dev/null 2>&1 || {
        msg "$RED" "[!] Lỗi khi xóa user $selected."
        pause
        return
    }

    chown proxy:proxy "$PASSWD_FILE" 2>/dev/null || true
    chmod 640 "$PASSWD_FILE"
    sync_users_file
    restart_squid
    msg "$GREEN" "[+] Xóa user $selected thành công."
    pause
}

restart_proxy() {
    msg "$WHITE" "[-] Đang khởi động lại proxy..."
    restart_squid
    if systemctl is-active --quiet squid; then
        msg "$GREEN" "[+] Khởi động lại proxy thành công."
    else
        msg "$RED" "[!] Lỗi khi khởi động lại proxy."
    fi
    pause
}

view_proxy_list() {
    local proxies=()
    mapfile -t proxies < <(list_proxies)
    if [[ ${#proxies[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không có proxy nào."
        pause
        return
    fi

    echo "Danh sách proxy hiện có (mọi user đều dùng chung được):"
    local i
    for i in "${!proxies[@]}"; do
        echo " [$((i+1))] ${proxies[$i]}"
    done
    pause
}

view_unadded_ips() {
    local ips=()
    mapfile -t ips < <(get_unadded_ips)
    if [[ ${#ips[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không còn IP nào chưa add proxy."
        pause
        return
    fi

    echo "Danh sách IP chưa có proxy (Tổng: ${#ips[@]}):"
    local i
    for i in "${!ips[@]}"; do
        echo " [$((i+1))] ${ips[$i]}"
    done
    pause
}

view_user_list() {
    local users=()
    mapfile -t users < <(list_users)
    if [[ ${#users[@]} -eq 0 ]]; then
        msg "$RED" "[!] Không có user nào."
        pause
        return
    fi

    echo "Danh sách user hiện có (dùng chung cho toàn bộ proxy):"
    local i
    for i in "${!users[@]}"; do
        echo " [$((i+1))] ${users[$i]}"
    done
    pause
}

main() {
    require_root
    ensure_packages
    ensure_files
    initial_setup

    while true; do
        clear
        display_header
        center_text "Menu Quản Lý Proxy"
        echo "[1] Quản lý Proxy"
        echo "[2] Quản lý User dùng chung"
        echo "[3] Khởi động lại Proxy"
        echo "[4] Xem danh sách"
        echo "[0] Thoát"
        read -r -p "-> Chọn một tùy chọn [0-4]: " choice
        case "$choice" in
            1)
                while true; do
                    clear
                    display_header
                    center_text "Quản lý Proxy"
                    echo "[1] Add Proxy"
                    echo "[2] Edit Proxy"
                    echo "[3] Xóa Proxy"
                    echo "[0] Quay lại"
                    read -r -p "-> Chọn một tùy chọn [0-3]: " sub_choice
                    case "$sub_choice" in
                        1) add_proxy ;;
                        2) edit_proxy ;;
                        3) delete_proxy ;;
                        0) break ;;
                        *) msg "$RED" "[!] Lựa chọn không hợp lệ."; pause ;;
                    esac
                done
                ;;
            2)
                while true; do
                    clear
                    display_header
                    center_text "Quản lý User dùng chung"
                    echo "[1] Add User"
                    echo "[2] Edit User"
                    echo "[3] Xóa User"
                    echo "[0] Quay lại"
                    read -r -p "-> Chọn một tùy chọn [0-3]: " sub_choice
                    case "$sub_choice" in
                        1) add_user ;;
                        2) edit_user ;;
                        3) delete_user ;;
                        0) break ;;
                        *) msg "$RED" "[!] Lựa chọn không hợp lệ."; pause ;;
                    esac
                done
                ;;
            3) restart_proxy ;;
            4)
                while true; do
                    clear
                    display_header
                    center_text "Xem danh sách"
                    echo "[1] Xem danh sách proxy hiện có"
                    echo "[2] Xem danh sách IP chưa có"
                    echo "[3] Xem danh sách user hiện có"
                    echo "[0] Quay lại"
                    read -r -p "-> Chọn một tùy chọn [0-3]: " sub_choice
                    case "$sub_choice" in
                        1) view_proxy_list ;;
                        2) view_unadded_ips ;;
                        3) view_user_list ;;
                        0) break ;;
                        *) msg "$RED" "[!] Lựa chọn không hợp lệ."; pause ;;
                    esac
                done
                ;;
            0) exit 0 ;;
            *) msg "$RED" "[!] Lựa chọn không hợp lệ."; pause ;;
        esac
    done
}

main "$@"
